### ISSUE TITLE
Add more information on how to test the installation

### ISSUE THREAD

**Issue by Kaljurand** [jcsilva/docker-kaldi-gstreamer-server#2]
I'm missing more detailed information in the README on how to verify that the installation was successful and the master and worker could be successfully started.

My `worker.log` looks good: there are no error messages and the last lines are:

```
2015-12-06 18:30:07 -    INFO:   __main__: Opening websocket connection to master server
2015-12-06 18:30:07 -    INFO:   __main__: Opened websocket connection to server
```

But testing with dictate.js and client.py does not produce any recognition results. E.g. I'm trying inside and outside the container:

```
python kaldi-gstreamer-server/kaldigstserver/client.py --uri ws://localhost:80/worker/ws/speech -r 8192 models/test/data/bill_gates-TED.mp3

python kaldigstserver/client.py --uri ws://localhost:8080/worker/ws/speech -r 8192 test/data/bill_gates-TED.mp3
```

but in both cases the server closes the socket and the client finishes without producing any output.

**Comment by jcsilva** [comment]
Hi. Could you please repeat your tests changing the uri? If possible, try these lines outside the container:

python kaldi-gstreamer-server/kaldigstserver/client.py --uri ws://localhost:80/**client**/ws/speech -r 8192 models/test/data/bill_gates-TED.mp3

python kaldigstserver/client.py --uri ws://localhost:8080/**client**/ws/speech -r 8192 test/data/bill_gates-TED.mp3

I think it's gonna work, since the worker was correctly started. I'll try to update the README.

**Comment by Kaljurand** [comment]
Thanks, replacing "worker" by "client" did the trick. Please mention it in the README.

**Comment by jcsilva** [comment]
I updated the README. I rewrote the "Testing" section. I think it's gonna be clearer ... Thanks for your comments!

**Comment by Kaljurand** [comment]
Thanks!
